<?php

declare(strict_types=1);

namespace Config;

use CodeIgniter\Config\BaseConfig;

/**
 * Content-hashed frontend assets. Regenerated by `npm run build`
 * (tools/hash-assets.mjs). Layout reads these; do not edit by hand.
 */
class Assets extends BaseConfig
{
    public string $css = 'app.00e841ae66a0.css';
    public string $js  = 'app.7f7fafd26730.js';
}
