<?php

declare(strict_types=1);

namespace Config;

use CodeIgniter\Config\BaseConfig;

/**
 * Content-hashed frontend assets. Regenerated by `npm run build`
 * (tools/hash-assets.mjs). Layout reads these; do not edit by hand.
 */
class Assets extends BaseConfig
{
    public string $css = 'app.759fac08c9bf.css';
    public string $js  = 'app.17a1569c8d96.js';
}
