<?php

declare(strict_types=1);

namespace WBS\Geo\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * Seeds baseline geo REFERENCE data (world-countries style) so location pickers,
 * phone-region defaults and venue/country fields resolve on a fresh deployment.
 *
 * This is a PRAGMATIC starter set — the six UN regions, a couple of subregions,
 * a representative set of countries with the deployment footprint (Ghana and
 * its West-African neighbours), AND (full-world decision 2026-09-24) the
 * complete states/regions + state seats/major cities for ALL seeded countries
 * so the group location directory's Country -> State -> City tree resolves. A production import can replace
 * this with the full ISO dataset later; the schema and lookups are identical, so
 * nothing downstream changes.
 *
 * Idempotent: countries upsert on iso2, regions/subregions on name. FK-safe order
 * (regions -> subregions -> countries).
 */
class GeoReferenceSeeder extends Seeder
{
    /** region name => list of subregion names */
    private const REGIONS = [
        'Africa'   => ['Western Africa', 'Eastern Africa', 'Northern Africa'],
        'Americas' => ['Northern America', 'South America'],
        'Asia'     => ['Southern Asia', 'Eastern Asia'],
        'Europe'   => ['Western Europe', 'Northern Europe'],
        'Oceania'  => ['Australia and New Zealand'],
        'Antarctic'=> [],
    ];

    /**
     * iso2 => [name, iso3, numeric, phonecode, capital, currency, currency_name,
     *          symbol, region, subregion, lat, lng]
     */
    private const COUNTRIES = [
        'GH' => ['Ghana', 'GHA', '288', '233', 'Accra', 'GHS', 'Ghanaian cedi', '₵', 'Africa', 'Western Africa', 7.9465, -1.0232],
        'NG' => ['Nigeria', 'NGA', '566', '234', 'Abuja', 'NGN', 'Nigerian naira', '₦', 'Africa', 'Western Africa', 9.0820, 8.6753],
        'TG' => ['Togo', 'TGO', '768', '228', 'Lomé', 'XOF', 'West African CFA franc', 'CFA', 'Africa', 'Western Africa', 8.6195, 0.8248],
        'CI' => ["Côte d'Ivoire", 'CIV', '384', '225', 'Yamoussoukro', 'XOF', 'West African CFA franc', 'CFA', 'Africa', 'Western Africa', 7.5400, -5.5471],
        'BF' => ['Burkina Faso', 'BFA', '854', '226', 'Ouagadougou', 'XOF', 'West African CFA franc', 'CFA', 'Africa', 'Western Africa', 12.2383, -1.5616],
        'BJ' => ['Benin', 'BEN', '204', '229', 'Porto-Novo', 'XOF', 'West African CFA franc', 'CFA', 'Africa', 'Western Africa', 9.3077, 2.3158],
        'KE' => ['Kenya', 'KEN', '404', '254', 'Nairobi', 'KES', 'Kenyan shilling', 'KSh', 'Africa', 'Eastern Africa', -0.0236, 37.9062],
        'ZA' => ['South Africa', 'ZAF', '710', '27', 'Pretoria', 'ZAR', 'South African rand', 'R', 'Africa', 'Eastern Africa', -30.5595, 22.9375],
        'EG' => ['Egypt', 'EGY', '818', '20', 'Cairo', 'EGP', 'Egyptian pound', 'E£', 'Africa', 'Northern Africa', 26.8206, 30.8025],
        'US' => ['United States', 'USA', '840', '1', 'Washington, D.C.', 'USD', 'United States dollar', '$', 'Americas', 'Northern America', 37.0902, -95.7129],
        'CA' => ['Canada', 'CAN', '124', '1', 'Ottawa', 'CAD', 'Canadian dollar', '$', 'Americas', 'Northern America', 56.1304, -106.3468],
        'BR' => ['Brazil', 'BRA', '076', '55', 'Brasília', 'BRL', 'Brazilian real', 'R$', 'Americas', 'South America', -14.2350, -51.9253],
        'GB' => ['United Kingdom', 'GBR', '826', '44', 'London', 'GBP', 'Pound sterling', '£', 'Europe', 'Northern Europe', 55.3781, -3.4360],
        'FR' => ['France', 'FRA', '250', '33', 'Paris', 'EUR', 'Euro', '€', 'Europe', 'Western Europe', 46.2276, 2.2137],
        'DE' => ['Germany', 'DEU', '276', '49', 'Berlin', 'EUR', 'Euro', '€', 'Europe', 'Western Europe', 51.1657, 10.4515],
        'IN' => ['India', 'IND', '356', '91', 'New Delhi', 'INR', 'Indian rupee', '₹', 'Asia', 'Southern Asia', 20.5937, 78.9629],
        'CN' => ['China', 'CHN', '156', '86', 'Beijing', 'CNY', 'Chinese yuan', '¥', 'Asia', 'Eastern Asia', 35.8617, 104.1954],
        'AU' => ['Australia', 'AUS', '036', '61', 'Canberra', 'AUD', 'Australian dollar', '$', 'Oceania', 'Australia and New Zealand', -25.2744, 133.7751],
    ];

    /**
     * iso2 => list of [name, state_code, type] for EVERY seeded country
     * (full-world decision 2026-09-24): completes the group location
     * directory's Country -> State/Region -> City reference layer.
     * Coordinates stay NULL — venues remain the geo source of truth.
     *
     * @var array<string,list<array{0:string,1:string,2:string}>>
     */
    private const STATES = [
        'GH' => [
            ['Greater Accra', 'GH-01', 'Region'],
            ['Ashanti', 'GH-02', 'Region'],
            ['Western', 'GH-03', 'Region'],
            ['Western North', 'GH-04', 'Region'],
            ['Central', 'GH-05', 'Region'],
            ['Eastern', 'GH-06', 'Region'],
            ['Volta', 'GH-07', 'Region'],
            ['Oti', 'GH-08', 'Region'],
            ['Northern', 'GH-09', 'Region'],
            ['Savannah', 'GH-10', 'Region'],
            ['North East', 'GH-11', 'Region'],
            ['Upper East', 'GH-12', 'Region'],
            ['Upper West', 'GH-13', 'Region'],
            ['Bono', 'GH-14', 'Region'],
            ['Bono East', 'GH-15', 'Region'],
            ['Ahafo', 'GH-16', 'Region'],
        ],
        'NG' => [
            ['Abia', 'NG-AB', 'State'],
            ['Adamawa', 'NG-AD', 'State'],
            ['Akwa Ibom', 'NG-AK', 'State'],
            ['Anambra', 'NG-AN', 'State'],
            ['Bauchi', 'NG-BA', 'State'],
            ['Bayelsa', 'NG-BY', 'State'],
            ['Benue', 'NG-BE', 'State'],
            ['Borno', 'NG-BO', 'State'],
            ['Cross River', 'NG-CR', 'State'],
            ['Delta', 'NG-DE', 'State'],
            ['Ebonyi', 'NG-EB', 'State'],
            ['Edo', 'NG-ED', 'State'],
            ['Ekiti', 'NG-EK', 'State'],
            ['Enugu', 'NG-EN', 'State'],
            ['Gombe', 'NG-GO', 'State'],
            ['Imo', 'NG-IM', 'State'],
            ['Jigawa', 'NG-JI', 'State'],
            ['Kaduna', 'NG-KD', 'State'],
            ['Kano', 'NG-KN', 'State'],
            ['Katsina', 'NG-KT', 'State'],
            ['Kebbi', 'NG-KE', 'State'],
            ['Kogi', 'NG-KO', 'State'],
            ['Kwara', 'NG-KW', 'State'],
            ['Lagos', 'NG-LA', 'State'],
            ['Nasarawa', 'NG-NA', 'State'],
            ['Niger', 'NG-NI', 'State'],
            ['Ogun', 'NG-OG', 'State'],
            ['Ondo', 'NG-ON', 'State'],
            ['Osun', 'NG-OS', 'State'],
            ['Oyo', 'NG-OY', 'State'],
            ['Plateau', 'NG-PL', 'State'],
            ['Rivers', 'NG-RI', 'State'],
            ['Sokoto', 'NG-SO', 'State'],
            ['Taraba', 'NG-TA', 'State'],
            ['Yobe', 'NG-YO', 'State'],
            ['Zamfara', 'NG-ZA', 'State'],
            ['Federal Capital Territory', 'NG-FC', 'Territory'],
        ],
        'TG' => [
            ['Centre', 'TG-02', 'Region'],
            ['Kara', 'TG-03', 'Region'],
            ['Maritime', 'TG-01', 'Region'],
            ['Plateaux', 'TG-04', 'Region'],
            ['Savanes', 'TG-05', 'Region'],
        ],
        'CI' => [
            ['Abidjan', 'CI-AB', 'District'],
            ['Yamoussoukro', 'CI-YM', 'District'],
            ['Agnéby-Tiassa', 'CI-AG', 'District'],
            ['Bafing', 'CI-BF', 'District'],
            ['Bas-Sassandra', 'CI-BS', 'District'],
            ['Denguélé', 'CI-DJ', 'District'],
            ['Gôh', 'CI-GH', 'District'],
            ['Lôh-Djiboua', 'CI-LD', 'District'],
            ['Nʼzi', 'CI-NZ', 'District'],
            ['Savanes', 'CI-SV', 'District'],
            ['Gontougo', 'CI-GT', 'District'],
            ['Bounkani', 'CI-BK', 'District'],
            ['Béré', 'CI-BR', 'District'],
            ['Guémon', 'CI-GM', 'District'],
        ],
        'BF' => [
            ['Boucle du Mouhoun', 'BF-01', 'Region'],
            ['Cascades', 'BF-02', 'Region'],
            ['Centre', 'BF-03', 'Region'],
            ['Centre-Est', 'BF-04', 'Region'],
            ['Centre-Nord', 'BF-05', 'Region'],
            ['Centre-Ouest', 'BF-06', 'Region'],
            ['Centre-Sud', 'BF-07', 'Region'],
            ['Est', 'BF-08', 'Region'],
            ['Hauts-Bassins', 'BF-09', 'Region'],
            ['Nord', 'BF-10', 'Region'],
            ['Plateau-Central', 'BF-11', 'Region'],
            ['Sahel', 'BF-12', 'Region'],
            ['Sud-Ouest', 'BF-13', 'Region'],
        ],
        'BJ' => [
            ['Alibori', 'BJ-AL', 'Department'],
            ['Atakora', 'BJ-AK', 'Department'],
            ['Atlantique', 'BJ-AT', 'Department'],
            ['Borgou', 'BJ-BO', 'Department'],
            ['Collines', 'BJ-CO', 'Department'],
            ['Donga', 'BJ-DO', 'Department'],
            ['Kouffo', 'BJ-KO', 'Department'],
            ['Littoral', 'BJ-LI', 'Department'],
            ['Mono', 'BJ-MO', 'Department'],
            ['Ouémé', 'BJ-OU', 'Department'],
            ['Plateau', 'BJ-PL', 'Department'],
            ['Zou', 'BJ-ZO', 'Department'],
        ],
        'KE' => [
            ['Baringo', 'KE-01', 'County'],
            ['Bomet', 'KE-02', 'County'],
            ['Bungoma', 'KE-03', 'County'],
            ['Busia', 'KE-04', 'County'],
            ['Elgeyo-Marakwet', 'KE-05', 'County'],
            ['Embu', 'KE-06', 'County'],
            ['Garissa', 'KE-07', 'County'],
            ['Homa Bay', 'KE-08', 'County'],
            ['Isiolo', 'KE-09', 'County'],
            ['Kajiado', 'KE-10', 'County'],
            ['Kakamega', 'KE-11', 'County'],
            ['Kericho', 'KE-12', 'County'],
            ['Kiambu', 'KE-13', 'County'],
            ['Kilifi', 'KE-14', 'County'],
            ['Kirinyaga', 'KE-15', 'County'],
            ['Kisii', 'KE-16', 'County'],
            ['Kisumu', 'KE-17', 'County'],
            ['Kitui', 'KE-18', 'County'],
            ['Kwale', 'KE-19', 'County'],
            ['Laikipia', 'KE-20', 'County'],
            ['Lamu', 'KE-21', 'County'],
            ['Machakos', 'KE-22', 'County'],
            ['Makueni', 'KE-23', 'County'],
            ['Mandera', 'KE-24', 'County'],
            ['Marsabit', 'KE-25', 'County'],
            ['Meru', 'KE-26', 'County'],
            ['Migori', 'KE-27', 'County'],
            ['Mombasa', 'KE-28', 'County'],
            ['Murang\'a', 'KE-29', 'County'],
            ['Nairobi', 'KE-30', 'County'],
            ['Nakuru', 'KE-31', 'County'],
            ['Nandi', 'KE-32', 'County'],
            ['Narok', 'KE-33', 'County'],
            ['Nyamira', 'KE-34', 'County'],
            ['Nyandarua', 'KE-35', 'County'],
            ['Nyeri', 'KE-36', 'County'],
            ['Samburu', 'KE-37', 'County'],
            ['Siaya', 'KE-38', 'County'],
            ['Taita-Taveta', 'KE-39', 'County'],
            ['Tana River', 'KE-40', 'County'],
            ['Tharaka-Nithi', 'KE-41', 'County'],
            ['Trans Nzoia', 'KE-42', 'County'],
            ['Turkana', 'KE-43', 'County'],
            ['Uasin Gishu', 'KE-44', 'County'],
            ['Vihiga', 'KE-45', 'County'],
            ['Wajir', 'KE-46', 'County'],
            ['West Pokot', 'KE-47', 'County'],
        ],
        'ZA' => [
            ['Eastern Cape', 'ZA-EC', 'Province'],
            ['Free State', 'ZA-FS', 'Province'],
            ['Gauteng', 'ZA-GP', 'Province'],
            ['KwaZulu-Natal', 'ZA-KZN', 'Province'],
            ['Limpopo', 'ZA-LP', 'Province'],
            ['Mpumalanga', 'ZA-MP', 'Province'],
            ['Northern Cape', 'ZA-NC', 'Province'],
            ['North West', 'ZA-NW', 'Province'],
            ['Western Cape', 'ZA-WC', 'Province'],
        ],
        'EG' => [
            ['Cairo', 'EG-C', 'Governorate'],
            ['Alexandria', 'EG-ALX', 'Governorate'],
            ['Port Said', 'EG-PTS', 'Governorate'],
            ['Suez', 'EG-SUZ', 'Governorate'],
            ['Damietta', 'EG-DAM', 'Governorate'],
            ['Dakahlia', 'EG-DK', 'Governorate'],
            ['Sharqia', 'EG-SHR', 'Governorate'],
            ['Qalyubia', 'EG-KB', 'Governorate'],
            ['Monufia', 'EG-MNF', 'Governorate'],
            ['Gharbia', 'EG-GB', 'Governorate'],
            ['Kafr El Sheikh', 'EG-KFS', 'Governorate'],
            ['Beheira', 'EG-BH', 'Governorate'],
            ['Ismailia', 'EG-IS', 'Governorate'],
            ['Faiyum', 'EG-FYM', 'Governorate'],
            ['Beni Suef', 'EG-BNS', 'Governorate'],
            ['Menia', 'EG-MN', 'Governorate'],
            ['Asyut', 'EG-AST', 'Governorate'],
            ['Sohag', 'EG-SHG', 'Governorate'],
            ['Qena', 'EG-KN', 'Governorate'],
            ['Luxor', 'EG-LX', 'Governorate'],
            ['Aswan', 'EG-ASN', 'Governorate'],
            ['Red Sea', 'EG-RS', 'Governorate'],
            ['Matrouh', 'EG-MT', 'Governorate'],
            ['North Sinai', 'EG-SIN', 'Governorate'],
            ['South Sinai', 'EG-JS', 'Governorate'],
            ['New Valley', 'EG-WAD', 'Governorate'],
            ['Giza', 'EG-GZ', 'Governorate'],
        ],
        'US' => [
            ['Alabama', 'AL', 'State'],
            ['Alaska', 'AK', 'State'],
            ['Arizona', 'AZ', 'State'],
            ['Arkansas', 'AR', 'State'],
            ['California', 'CA', 'State'],
            ['Colorado', 'CO', 'State'],
            ['Connecticut', 'CT', 'State'],
            ['Delaware', 'DE', 'State'],
            ['District of Columbia', 'DC', 'District'],
            ['Florida', 'FL', 'State'],
            ['Georgia', 'GA', 'State'],
            ['Hawaii', 'HI', 'State'],
            ['Idaho', 'ID', 'State'],
            ['Illinois', 'IL', 'State'],
            ['Indiana', 'IN', 'State'],
            ['Iowa', 'IA', 'State'],
            ['Kansas', 'KS', 'State'],
            ['Kentucky', 'KY', 'State'],
            ['Louisiana', 'LA', 'State'],
            ['Maine', 'ME', 'State'],
            ['Maryland', 'MD', 'State'],
            ['Massachusetts', 'MA', 'State'],
            ['Michigan', 'MI', 'State'],
            ['Minnesota', 'MN', 'State'],
            ['Mississippi', 'MS', 'State'],
            ['Missouri', 'MO', 'State'],
            ['Montana', 'MT', 'State'],
            ['Nebraska', 'NE', 'State'],
            ['Nevada', 'NV', 'State'],
            ['New Hampshire', 'NH', 'State'],
            ['New Jersey', 'NJ', 'State'],
            ['New Mexico', 'NM', 'State'],
            ['New York', 'NY', 'State'],
            ['North Carolina', 'NC', 'State'],
            ['North Dakota', 'ND', 'State'],
            ['Ohio', 'OH', 'State'],
            ['Oklahoma', 'OK', 'State'],
            ['Oregon', 'OR', 'State'],
            ['Pennsylvania', 'PA', 'State'],
            ['Rhode Island', 'RI', 'State'],
            ['South Carolina', 'SC', 'State'],
            ['South Dakota', 'SD', 'State'],
            ['Tennessee', 'TN', 'State'],
            ['Texas', 'TX', 'State'],
            ['Utah', 'UT', 'State'],
            ['Vermont', 'VT', 'State'],
            ['Virginia', 'VA', 'State'],
            ['Washington', 'WA', 'State'],
            ['West Virginia', 'WV', 'State'],
            ['Wisconsin', 'WI', 'State'],
            ['Wyoming', 'WY', 'State'],
        ],
        'CA' => [
            ['Alberta', 'AB', 'Province'],
            ['British Columbia', 'BC', 'Province'],
            ['Manitoba', 'MB', 'Province'],
            ['New Brunswick', 'NB', 'Province'],
            ['Newfoundland and Labrador', 'NL', 'Province'],
            ['Nova Scotia', 'NS', 'Province'],
            ['Ontario', 'ON', 'Province'],
            ['Prince Edward Island', 'PE', 'Province'],
            ['Quebec', 'QC', 'Province'],
            ['Saskatchewan', 'SK', 'Province'],
            ['Northwest Territories', 'NT', 'Territory'],
            ['Nunavut', 'NU', 'Territory'],
            ['Yukon', 'YT', 'Territory'],
        ],
        'BR' => [
            ['Acre', 'BR-AC', 'State'],
            ['Alagoas', 'BR-AL', 'State'],
            ['Amapá', 'BR-AP', 'State'],
            ['Amazonas', 'BR-AM', 'State'],
            ['Bahia', 'BR-BA', 'State'],
            ['Ceará', 'BR-CE', 'State'],
            ['Distrito Federal', 'BR-DF', 'Federal District'],
            ['Espírito Santo', 'BR-ES', 'State'],
            ['Goiás', 'BR-GO', 'State'],
            ['Maranhão', 'BR-MA', 'State'],
            ['Mato Grosso', 'BR-MT', 'State'],
            ['Mato Grosso do Sul', 'BR-MS', 'State'],
            ['Minas Gerais', 'BR-MG', 'State'],
            ['Pará', 'BR-PA', 'State'],
            ['Paraíba', 'BR-PB', 'State'],
            ['Paraná', 'BR-PR', 'State'],
            ['Pernambuco', 'BR-PE', 'State'],
            ['Piauí', 'BR-PI', 'State'],
            ['Rio de Janeiro', 'BR-RJ', 'State'],
            ['Rio Grande do Norte', 'BR-RN', 'State'],
            ['Rio Grande do Sul', 'BR-RS', 'State'],
            ['Rondônia', 'BR-RO', 'State'],
            ['Roraima', 'BR-RR', 'State'],
            ['Santa Catarina', 'BR-SC', 'State'],
            ['São Paulo', 'BR-SP', 'State'],
            ['Sergipe', 'BR-SE', 'State'],
            ['Tocantins', 'BR-TO', 'State'],
        ],
        'GB' => [
            ['England', 'GB-ENG', 'Country'],
            ['Scotland', 'GB-SCT', 'Country'],
            ['Wales', 'GB-WLS', 'Country'],
            ['Northern Ireland', 'GB-NIR', 'Country'],
        ],
        'FR' => [
            ['Île-de-France', 'FR-IDF', 'Region'],
            ['Auvergne-Rhône-Alpes', 'FR-ARA', 'Region'],
            ['Bourgogne-Franche-Comté', 'FR-BFC', 'Region'],
            ['Bretagne', 'FR-BRE', 'Region'],
            ['Centre-Val de Loire', 'FR-CVL', 'Region'],
            ['Corse', 'FR-20R', 'Region'],
            ['Grand Est', 'FR-GES', 'Region'],
            ['Hauts-de-France', 'FR-HDF', 'Region'],
            ['Normandie', 'FR-NOR', 'Region'],
            ['Nouvelle-Aquitaine', 'FR-NAQ', 'Region'],
            ['Occitanie', 'FR-OCC', 'Region'],
            ['Pays de la Loire', 'FR-PDL', 'Region'],
            ['Provence-Alpes-Côte dʼAzur', 'FR-PAC', 'Region'],
            ['Guadeloupe', 'FR-GP', 'Region'],
            ['Guyane', 'FR-GF', 'Region'],
            ['Martinique', 'FR-MQ', 'Region'],
            ['La Réunion', 'FR-RE', 'Region'],
            ['Mayotte', 'FR-YT', 'Region'],
        ],
        'DE' => [
            ['Baden-Württemberg', 'DE-BW', 'State'],
            ['Bavaria', 'DE-BY', 'State'],
            ['Berlin', 'DE-BE', 'State'],
            ['Brandenburg', 'DE-BB', 'State'],
            ['Bremen', 'DE-HB', 'State'],
            ['Hamburg', 'DE-HH', 'State'],
            ['Hesse', 'DE-HE', 'State'],
            ['Lower Saxony', 'DE-NI', 'State'],
            ['Mecklenburg-Vorpommern', 'DE-MV', 'State'],
            ['North Rhine-Westphalia', 'DE-NW', 'State'],
            ['Rhineland-Palatinate', 'DE-RP', 'State'],
            ['Saarland', 'DE-SL', 'State'],
            ['Saxony', 'DE-SN', 'State'],
            ['Saxony-Anhalt', 'DE-ST', 'State'],
            ['Schleswig-Holstein', 'DE-SH', 'State'],
            ['Thuringia', 'DE-TH', 'State'],
        ],
        'IN' => [
            ['Andhra Pradesh', 'IN-AP', 'State'],
            ['Arunachal Pradesh', 'IN-AR', 'State'],
            ['Assam', 'IN-AS', 'State'],
            ['Bihar', 'IN-BR', 'State'],
            ['Chhattisgarh', 'IN-CT', 'State'],
            ['Goa', 'IN-GA', 'State'],
            ['Gujarat', 'IN-GJ', 'State'],
            ['Haryana', 'IN-HR', 'State'],
            ['Himachal Pradesh', 'IN-HP', 'State'],
            ['Jharkhand', 'IN-JH', 'State'],
            ['Karnataka', 'IN-KA', 'State'],
            ['Kerala', 'IN-KL', 'State'],
            ['Madhya Pradesh', 'IN-MP', 'State'],
            ['Maharashtra', 'IN-MH', 'State'],
            ['Manipur', 'IN-MN', 'State'],
            ['Meghalaya', 'IN-ML', 'State'],
            ['Mizoram', 'IN-MZ', 'State'],
            ['Nagaland', 'IN-NL', 'State'],
            ['Odisha', 'IN-OR', 'State'],
            ['Punjab', 'IN-PB', 'State'],
            ['Rajasthan', 'IN-RJ', 'State'],
            ['Sikkim', 'IN-SK', 'State'],
            ['Tamil Nadu', 'IN-TN', 'State'],
            ['Telangana', 'IN-TS', 'State'],
            ['Tripura', 'IN-TR', 'State'],
            ['Uttar Pradesh', 'IN-UP', 'State'],
            ['Uttarakhand', 'IN-UK', 'State'],
            ['West Bengal', 'IN-WB', 'State'],
            ['Andaman and Nicobar Islands', 'IN-AN', 'Union Territory'],
            ['Chandigarh', 'IN-CH', 'Union Territory'],
            ['Dadra and Nagar Haveli and Daman and Diu', 'IN-DH', 'Union Territory'],
            ['Delhi', 'IN-DL', 'Union Territory'],
            ['Jammu and Kashmir', 'IN-JK', 'Union Territory'],
            ['Ladakh', 'IN-LA', 'Union Territory'],
            ['Lakshadweep', 'IN-LD', 'Union Territory'],
            ['Puducherry', 'IN-PY', 'Union Territory'],
        ],
        'CN' => [
            ['Beijing', 'CN-BJ', 'Province'],
            ['Tianjin', 'CN-TJ', 'Province'],
            ['Hebei', 'CN-HE', 'Province'],
            ['Shanxi', 'CN-SX', 'Province'],
            ['Inner Mongolia', 'CN-NM', 'Province'],
            ['Liaoning', 'CN-LN', 'Province'],
            ['Jilin', 'CN-JL', 'Province'],
            ['Heilongjiang', 'CN-HL', 'Province'],
            ['Shanghai', 'CN-SH', 'Province'],
            ['Jiangsu', 'CN-JS', 'Province'],
            ['Zhejiang', 'CN-ZJ', 'Province'],
            ['Anhui', 'CN-AH', 'Province'],
            ['Fujian', 'CN-FJ', 'Province'],
            ['Jiangxi', 'CN-JX', 'Province'],
            ['Shandong', 'CN-SD', 'Province'],
            ['Henan', 'CN-HA', 'Province'],
            ['Hubei', 'CN-HB', 'Province'],
            ['Hunan', 'CN-HN', 'Province'],
            ['Guangdong', 'CN-GD', 'Province'],
            ['Guangxi', 'CN-GX', 'Province'],
            ['Hainan', 'CN-HI', 'Province'],
            ['Chongqing', 'CN-CQ', 'Province'],
            ['Sichuan', 'CN-SC', 'Province'],
            ['Guizhou', 'CN-GZ', 'Province'],
            ['Yunnan', 'CN-YN', 'Province'],
            ['Tibet', 'CN-XZ', 'Province'],
            ['Shaanxi', 'CN-SN', 'Province'],
            ['Gansu', 'CN-GS', 'Province'],
            ['Qinghai', 'CN-QH', 'Province'],
            ['Ningxia', 'CN-NX', 'Province'],
            ['Xinjiang', 'CN-XJ', 'Province'],
            ['Taiwan', 'CN-TW', 'Province'],
            ['Hong Kong', 'CN-HK', 'Special Region'],
            ['Macao', 'CN-MO', 'Special Region'],
        ],
        'AU' => [
            ['New South Wales', 'AU-NSW', 'State'],
            ['Victoria', 'AU-VIC', 'State'],
            ['Queensland', 'AU-QLD', 'State'],
            ['South Australia', 'AU-SA', 'State'],
            ['Western Australia', 'AU-WA', 'State'],
            ['Tasmania', 'AU-TAS', 'State'],
            ['Northern Territory', 'AU-NT', 'Territory'],
            ['Australian Capital Territory', 'AU-ACT', 'Territory'],
        ],
    ];

    /**
     * iso2 => list of [state_code, city name] — each state's seat plus
     * major extras for the large countries. Coordinates stay NULL.
     *
     * @var array<string,list<array{0:string,1:string}>>
     */
    private const CITIES = [
        'GH' => [
            ['GH-01', 'Accra'],
            ['GH-01', 'Tema'],
            ['GH-02', 'Kumasi'],
            ['GH-02', 'Obuasi'],
            ['GH-03', 'Sekondi-Takoradi'],
            ['GH-04', 'Wiawso'],
            ['GH-05', 'Cape Coast'],
            ['GH-05', 'Winneba'],
            ['GH-06', 'Koforidua'],
            ['GH-06', 'Nkawkaw'],
            ['GH-07', 'Ho'],
            ['GH-08', 'Dambai'],
            ['GH-09', 'Tamale'],
            ['GH-10', 'Damongo'],
            ['GH-11', 'Nalerigu'],
            ['GH-12', 'Bolgatanga'],
            ['GH-13', 'Wa'],
            ['GH-14', 'Sunyani'],
            ['GH-15', 'Techiman'],
            ['GH-16', 'Goaso'],
        ],
        'NG' => [
            ['NG-FC', 'Abuja'],
            ['NG-LA', 'Lagos'],
            ['NG-KN', 'Kano'],
            ['NG-AB', 'Umuahia'],
            ['NG-AD', 'Yola'],
            ['NG-AK', 'Uyo'],
            ['NG-AN', 'Awka'],
            ['NG-BA', 'Bauchi'],
            ['NG-BY', 'Yenagoa'],
            ['NG-BE', 'Makurdi'],
            ['NG-BO', 'Maiduguri'],
            ['NG-CR', 'Calabar'],
            ['NG-DE', 'Asaba'],
            ['NG-EB', 'Abakaliki'],
            ['NG-ED', 'Benin City'],
            ['NG-EK', 'Ado-Ekiti'],
            ['NG-EN', 'Enugu'],
            ['NG-GO', 'Gombe'],
            ['NG-IM', 'Owerri'],
            ['NG-JI', 'Dutse'],
            ['NG-KD', 'Kaduna'],
            ['NG-KT', 'Katsina'],
            ['NG-KE', 'Birnin Kebbi'],
            ['NG-KO', 'Lokoja'],
            ['NG-KW', 'Ilorin'],
            ['NG-NA', 'Lafia'],
            ['NG-NI', 'Minna'],
            ['NG-OG', 'Abeokuta'],
            ['NG-ON', 'Akure'],
            ['NG-OS', 'Osogbo'],
            ['NG-OY', 'Ibadan'],
            ['NG-PL', 'Jos'],
            ['NG-RI', 'Port Harcourt'],
            ['NG-SO', 'Sokoto'],
            ['NG-TA', 'Jalingo'],
            ['NG-YO', 'Damaturu'],
            ['NG-ZA', 'Gusau'],
        ],
        'TG' => [
            ['TG-01', 'Lomé'],
            ['TG-02', 'Sokodé'],
            ['TG-03', 'Kara'],
            ['TG-04', 'Atakpamé'],
            ['TG-05', 'Dapaong'],
        ],
        'CI' => [
            ['CI-AB', 'Abidjan'],
            ['CI-YM', 'Yamoussoukro'],
            ['CI-AG', 'Agboville'],
            ['CI-BF', 'Touba'],
            ['CI-BS', 'Grand-Bassam'],
            ['CI-DJ', 'Odienné'],
            ['CI-GH', 'Daloa'],
            ['CI-LD', 'Divo'],
            ['CI-NZ', 'Katiola'],
            ['CI-SV', 'Korhogo'],
            ['CI-GT', 'Mankono'],
            ['CI-BK', 'Bondoukou'],
            ['CI-BR', 'Séguela'],
            ['CI-GM', 'Duékoué'],
        ],
        'BF' => [
            ['BF-01', 'Dédougou'],
            ['BF-02', 'Banfora'],
            ['BF-03', 'Ouagadougou'],
            ['BF-04', 'Tenkodogo'],
            ['BF-05', 'Kaya'],
            ['BF-06', 'Koudougou'],
            ['BF-07', 'Ziniaré'],
            ['BF-08', 'Bogandé'],
            ['BF-09', 'Bobo-Dioulasso'],
            ['BF-10', 'Dori'],
            ['BF-11', 'Zorgho'],
            ['BF-12', 'Djibo'],
            ['BF-13', 'Gaoua'],
        ],
        'BJ' => [
            ['BJ-AL', 'Kandi'],
            ['BJ-AK', 'Natitingou'],
            ['BJ-AT', 'Bohicon'],
            ['BJ-BO', 'Parakou'],
            ['BJ-CO', 'Savalou'],
            ['BJ-DO', 'Djougou'],
            ['BJ-KO', 'Aplahoué'],
            ['BJ-LI', 'Cotonou'],
            ['BJ-MO', 'Lokossa'],
            ['BJ-OU', 'Porto-Novo'],
            ['BJ-PL', 'Pobè'],
            ['BJ-ZO', 'Abomey-Calavi'],
        ],
        'KE' => [
            ['KE-30', 'Nairobi'],
            ['KE-28', 'Mombasa'],
            ['KE-17', 'Kisumu'],
            ['KE-01', 'Kabarnet'],
            ['KE-02', 'Bomet'],
            ['KE-03', 'Bungoma'],
            ['KE-04', 'Busia'],
            ['KE-05', 'Iten'],
            ['KE-06', 'Embu'],
            ['KE-07', 'Garissa'],
            ['KE-08', 'Homa Bay'],
            ['KE-09', 'Isiolo'],
            ['KE-10', 'Kajiado'],
            ['KE-11', 'Kakamega'],
            ['KE-12', 'Kericho'],
            ['KE-13', 'Kiambu'],
            ['KE-14', 'Kilifi'],
            ['KE-15', 'Kutus'],
            ['KE-16', 'Kisii'],
            ['KE-18', 'Kitui'],
            ['KE-19', 'Kwale'],
            ['KE-20', 'Nyahururu'],
            ['KE-21', 'Lamu'],
            ['KE-22', 'Machakos'],
            ['KE-23', 'Wote'],
            ['KE-24', 'Mandera'],
            ['KE-25', 'Marsabit'],
            ['KE-26', 'Meru'],
            ['KE-27', 'Migori'],
            ['KE-29', 'Murang\'a'],
            ['KE-31', 'Nakuru'],
            ['KE-32', 'Kapsabet'],
            ['KE-33', 'Narok'],
            ['KE-34', 'Nyamira'],
            ['KE-35', 'Ol Kalou'],
            ['KE-36', 'Nyeri'],
            ['KE-37', 'Maralal'],
            ['KE-38', 'Siaya'],
            ['KE-39', 'Wundanyi'],
            ['KE-40', 'Garsen'],
            ['KE-41', 'Chuka'],
            ['KE-42', 'Kitale'],
            ['KE-43', 'Lodwar'],
            ['KE-44', 'Eldoret'],
            ['KE-45', 'Vihiga'],
            ['KE-46', 'Wajir'],
            ['KE-47', 'Kapenguria'],
        ],
        'ZA' => [
            ['ZA-EC', 'Bhisho'],
            ['ZA-FS', 'Bloemfontein'],
            ['ZA-GP', 'Johannesburg'],
            ['ZA-KZN', 'Pietermaritzburg'],
            ['ZA-LP', 'Polokwane'],
            ['ZA-MP', 'Mbombela'],
            ['ZA-NC', 'Cape Town'],
            ['ZA-NW', 'Mahikeng'],
            ['ZA-WC', 'Cape Town'],
        ],
        'EG' => [
            ['EG-C', 'Cairo'],
            ['EG-ALX', 'Alexandria'],
            ['EG-PTS', 'Port Said'],
            ['EG-SUZ', 'Suez'],
            ['EG-DAM', 'Damietta'],
            ['EG-SHR', 'Zagazig'],
            ['EG-KB', 'Banha'],
            ['EG-MNF', 'Shebin El Kom'],
            ['EG-GB', 'Tanta'],
            ['EG-KFS', 'Kafr El Sheikh'],
            ['EG-BH', 'Damanhur'],
            ['EG-IS', 'Ismailia'],
            ['EG-FYM', 'Faiyum'],
            ['EG-BNS', 'Beni Suef'],
            ['EG-MN', 'Menia'],
            ['EG-AST', 'Asyut'],
            ['EG-SHG', 'Sohag'],
            ['EG-KN', 'Qena'],
            ['EG-LX', 'Luxor'],
            ['EG-ASN', 'Aswan'],
            ['EG-RS', 'Hurghada'],
            ['EG-MT', 'Matrouh'],
            ['EG-SIN', 'El Arish'],
            ['EG-JS', 'El Tor'],
            ['EG-WAD', 'Kharga'],
            ['EG-GZ', 'Giza'],
        ],
        'US' => [
            ['AL', 'Montgomery'],
            ['AK', 'Juneau'],
            ['AZ', 'Phoenix'],
            ['AR', 'Little Rock'],
            ['CA', 'Sacramento'],
            ['CA', 'Los Angeles'],
            ['CA', 'San Francisco'],
            ['CA', 'San Diego'],
            ['CO', 'Denver'],
            ['CT', 'Hartford'],
            ['DE', 'Dover'],
            ['DC', 'Washington'],
            ['FL', 'Tallahassee'],
            ['FL', 'Miami'],
            ['FL', 'Orlando'],
            ['GA', 'Atlanta'],
            ['HI', 'Honolulu'],
            ['ID', 'Boise'],
            ['IL', 'Springfield'],
            ['IL', 'Chicago'],
            ['IN', 'Indianapolis'],
            ['IA', 'Des Moines'],
            ['KS', 'Topeka'],
            ['KY', 'Frankfort'],
            ['LA', 'Baton Rouge'],
            ['ME', 'Augusta'],
            ['MD', 'Annapolis'],
            ['MA', 'Boston'],
            ['MI', 'Lansing'],
            ['MN', 'Saint Paul'],
            ['MS', 'Jackson'],
            ['MO', 'Jefferson City'],
            ['MT', 'Helena'],
            ['NE', 'Lincoln'],
            ['NV', 'Carson City'],
            ['NH', 'Concord'],
            ['NJ', 'Trenton'],
            ['NM', 'Santa Fe'],
            ['NY', 'Albany'],
            ['NY', 'New York'],
            ['NC', 'Raleigh'],
            ['ND', 'Bismarck'],
            ['OH', 'Columbus'],
            ['OK', 'Oklahoma City'],
            ['OR', 'Salem'],
            ['PA', 'Harrisburg'],
            ['PA', 'Philadelphia'],
            ['RI', 'Providence'],
            ['SC', 'Columbia'],
            ['SD', 'Pierre'],
            ['TN', 'Nashville'],
            ['TX', 'Austin'],
            ['TX', 'Houston'],
            ['TX', 'Dallas'],
            ['TX', 'San Antonio'],
            ['UT', 'Salt Lake City'],
            ['VT', 'Montpelier'],
            ['VA', 'Richmond'],
            ['WA', 'Olympia'],
            ['WA', 'Seattle'],
            ['WV', 'Charleston'],
            ['WI', 'Madison'],
            ['WY', 'Cheyenne'],
        ],
        'CA' => [
            ['AB', 'Edmonton'],
            ['AB', 'Calgary'],
            ['BC', 'Victoria'],
            ['BC', 'Vancouver'],
            ['MB', 'Winnipeg'],
            ['NB', 'Fredericton'],
            ['NB', 'Moncton'],
            ['NL', 'St. John\'s'],
            ['NS', 'Halifax'],
            ['ON', 'Toronto'],
            ['ON', 'Ottawa'],
            ['PE', 'Charlottetown'],
            ['QC', 'Quebec City'],
            ['QC', 'Montreal'],
            ['SK', 'Regina'],
            ['SK', 'Saskatoon'],
            ['NT', 'Yellowknife'],
            ['NU', 'Iqaluit'],
            ['YT', 'Whitehorse'],
        ],
        'BR' => [
            ['BR-AC', 'Rio Branco'],
            ['BR-AL', 'Maceió'],
            ['BR-AP', 'Macapá'],
            ['BR-AM', 'Manaus'],
            ['BR-BA', 'Salvador'],
            ['BR-CE', 'Fortaleza'],
            ['BR-DF', 'Brasília'],
            ['BR-ES', 'Vitória'],
            ['BR-GO', 'Goiânia'],
            ['BR-MA', 'São Luís'],
            ['BR-MT', 'Cuiabá'],
            ['BR-MS', 'Campo Grande'],
            ['BR-MG', 'Belo Horizonte'],
            ['BR-PA', 'Belém'],
            ['BR-PB', 'João Pessoa'],
            ['BR-PR', 'Curitiba'],
            ['BR-PE', 'Recife'],
            ['BR-PI', 'Teresina'],
            ['BR-RJ', 'Rio de Janeiro'],
            ['BR-RN', 'Natal'],
            ['BR-RS', 'Porto Alegre'],
            ['BR-RO', 'Porto Velho'],
            ['BR-RR', 'Boa Vista'],
            ['BR-SC', 'Florianópolis'],
            ['BR-SP', 'São Paulo'],
            ['BR-SE', 'Aracaju'],
            ['BR-TO', 'Palmas'],
        ],
        'GB' => [
            ['GB-ENG', 'London'],
            ['GB-SCT', 'Edinburgh'],
            ['GB-WLS', 'Cardiff'],
            ['GB-NIR', 'Belfast'],
        ],
        'FR' => [
            ['FR-IDF', 'Paris'],
            ['FR-ARA', 'Lyon'],
            ['FR-BFC', 'Dijon'],
            ['FR-BRE', 'Rennes'],
            ['FR-CVL', 'Orléans'],
            ['FR-20R', 'Ajaccio'],
            ['FR-GES', 'Strasbourg'],
            ['FR-HDF', 'Lille'],
            ['FR-NOR', 'Rouen'],
            ['FR-NAQ', 'Bordeaux'],
            ['FR-OCC', 'Toulouse'],
            ['FR-PDL', 'Nantes'],
            ['FR-PAC', 'Marseille'],
            ['FR-GP', 'Basse-Terre'],
            ['FR-GF', 'Cayenne'],
            ['FR-MQ', 'Fort-de-France'],
            ['FR-RE', 'Saint-Denis'],
            ['FR-YT', 'Mamoudzou'],
        ],
        'DE' => [
            ['DE-BW', 'Stuttgart'],
            ['DE-BY', 'Munich'],
            ['DE-BE', 'Berlin'],
            ['DE-BB', 'Potsdam'],
            ['DE-HB', 'Bremen'],
            ['DE-HH', 'Hamburg'],
            ['DE-HE', 'Wiesbaden'],
            ['DE-NI', 'Hanover'],
            ['DE-MV', 'Schwerin'],
            ['DE-NW', 'Düsseldorf'],
            ['DE-RP', 'Mainz'],
            ['DE-SL', 'Saarbrücken'],
            ['DE-SN', 'Dresden'],
            ['DE-ST', 'Magdeburg'],
            ['DE-SH', 'Kiel'],
            ['DE-TH', 'Erfurt'],
        ],
        'IN' => [
            ['IN-AP', 'Amaravati'],
            ['IN-AR', 'Itanagar'],
            ['IN-AS', 'Dispur'],
            ['IN-BR', 'Patna'],
            ['IN-CT', 'Raipur'],
            ['IN-GA', 'Panaji'],
            ['IN-GJ', 'Gandhinagar'],
            ['IN-HR', 'Chandigarh'],
            ['IN-HP', 'Shimla'],
            ['IN-JH', 'Ranchi'],
            ['IN-KA', 'Bengaluru'],
            ['IN-KL', 'Thiruvananthapuram'],
            ['IN-MP', 'Bhopal'],
            ['IN-MH', 'Mumbai'],
            ['IN-MN', 'Imphal'],
            ['IN-ML', 'Shillong'],
            ['IN-MZ', 'Aizawl'],
            ['IN-NL', 'Kohima'],
            ['IN-OR', 'Bhubaneswar'],
            ['IN-PB', 'Chandigarh'],
            ['IN-RJ', 'Jaipur'],
            ['IN-SK', 'Gangtok'],
            ['IN-TN', 'Chennai'],
            ['IN-TS', 'Hyderabad'],
            ['IN-TR', 'Agartala'],
            ['IN-UP', 'Lucknow'],
            ['IN-UK', 'Dehradun'],
            ['IN-WB', 'Kolkata'],
            ['IN-AN', 'Port Blair'],
            ['IN-CH', 'Chandigarh'],
            ['IN-DH', 'Silvassa'],
            ['IN-DL', 'New Delhi'],
            ['IN-JK', 'Srinagar'],
            ['IN-LA', 'Leh'],
            ['IN-LD', 'Kavaratti'],
            ['IN-PY', 'Puducherry'],
        ],
        'CN' => [
            ['CN-BJ', 'Beijing'],
            ['CN-TJ', 'Tianjin'],
            ['CN-HE', 'Shijiazhuang'],
            ['CN-SX', 'Taiyuan'],
            ['CN-NM', 'Hohhot'],
            ['CN-LN', 'Shenyang'],
            ['CN-JL', 'Changchun'],
            ['CN-HL', 'Harbin'],
            ['CN-SH', 'Shanghai'],
            ['CN-JS', 'Nanjing'],
            ['CN-ZJ', 'Hangzhou'],
            ['CN-AH', 'Hefei'],
            ['CN-FJ', 'Fuzhou'],
            ['CN-JX', 'Nanchang'],
            ['CN-SD', 'Jinan'],
            ['CN-HA', 'Zhengzhou'],
            ['CN-HB', 'Wuhan'],
            ['CN-HN', 'Changsha'],
            ['CN-GD', 'Guangzhou'],
            ['CN-GX', 'Nanning'],
            ['CN-HI', 'Haikou'],
            ['CN-CQ', 'Chongqing'],
            ['CN-SC', 'Chengdu'],
            ['CN-GZ', 'Guiyang'],
            ['CN-YN', 'Kunming'],
            ['CN-XZ', 'Lhasa'],
            ['CN-SN', 'Xi\'an'],
            ['CN-GS', 'Lanzhou'],
            ['CN-QH', 'Xining'],
            ['CN-NX', 'Yinchuan'],
            ['CN-XJ', 'Urumqi'],
            ['CN-TW', 'Taipei'],
            ['CN-HK', 'Hong Kong'],
            ['CN-MO', 'Macao'],
        ],
        'AU' => [
            ['AU-NSW', 'Sydney'],
            ['AU-VIC', 'Melbourne'],
            ['AU-QLD', 'Brisbane'],
            ['AU-SA', 'Adelaide'],
            ['AU-WA', 'Perth'],
            ['AU-TAS', 'Hobart'],
            ['AU-NT', 'Darwin'],
            ['AU-ACT', 'Canberra'],
        ],
    ];

    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        // 1. Regions (upsert on name) -> id map.
        $regionId = [];
        foreach (array_keys(self::REGIONS) as $name) {
            $row = $this->db->table('regions')->where('name', $name)->get()->getRowArray();
            if ($row === null) {
                $this->db->table('regions')->insert(['name' => $name, 'created_at' => $now]);
                $regionId[$name] = (int) $this->db->insertID();
            } else {
                $regionId[$name] = (int) $row['id'];
            }
        }

        // 2. Subregions (upsert on region+name) -> id map keyed by subregion name.
        $subId = [];
        foreach (self::REGIONS as $rName => $subs) {
            foreach ($subs as $sName) {
                $row = $this->db->table('subregions')
                    ->where('region_id', $regionId[$rName])->where('name', $sName)
                    ->get()->getRowArray();
                if ($row === null) {
                    $this->db->table('subregions')->insert([
                        'name' => $sName, 'region_id' => $regionId[$rName], 'created_at' => $now,
                    ]);
                    $subId[$sName] = (int) $this->db->insertID();
                } else {
                    $subId[$sName] = (int) $row['id'];
                }
            }
        }

        // 3. Countries (upsert on iso2).
        $count = 0;
        foreach (self::COUNTRIES as $iso2 => $c) {
            [$name, $iso3, $numeric, $phone, $capital, $ccy, $ccyName, $symbol, $region, $sub, $lat, $lng] = $c;
            $row = [
                'name'            => $name,
                'iso2'            => $iso2,
                'iso3'            => $iso3,
                'numeric_code'    => $numeric,
                'phonecode'       => $phone,
                'capital'         => $capital,
                'currency'        => $ccy,
                'currency_name'   => $ccyName,
                'currency_symbol' => $symbol,
                'region_id'       => $regionId[$region] ?? null,
                'subregion_id'    => $subId[$sub] ?? null,
                'latitude'        => $lat,
                'longitude'       => $lng,
                'updated_at'      => $now,
            ];
            $existing = $this->db->table('countries')->where('iso2', $iso2)->get()->getRowArray();
            if ($existing !== null) {
                $this->db->table('countries')->where('id', $existing['id'])->update($row);
            } else {
                $this->db->table('countries')->insert($row + ['created_at' => $now]);
                $count++;
            }
        }

        // 4. States / regions (upsert on country + state_code) -> id map.
        //    Resolve each country's id (insert path already wrote the row).
        $countryId = [];
        $stateCount = 0;
        $stateId = [];
        foreach (self::STATES as $iso2 => $rows) {
            $cRow = $this->db->table('countries')->where('iso2', $iso2)->get()->getRowArray();
            if ($cRow === null) {
                continue; // country missing (partial seeding) — skip its states
            }
            $countryId[$iso2] = (int) $cRow['id'];
            foreach ($rows as [$sName, $sCode, $sType]) {
                $row = $this->db->table('states')
                    ->where('country_id', $countryId[$iso2])->where('state_code', $sCode)
                    ->get()->getRowArray();
                if ($row === null) {
                    $this->db->table('states')->insert([
                        'name'         => $sName,
                        'country_id'   => $countryId[$iso2],
                        'country_code' => $iso2,
                        'state_code'   => $sCode,
                        'type'         => $sType,
                        'created_at'   => $now,
                        'updated_at'   => $now,
                    ]);
                    $stateId[$iso2 . ':' . $sCode] = (int) $this->db->insertID();
                    $stateCount++;
                } else {
                    $stateId[$iso2 . ':' . $sCode] = (int) $row['id'];
                }
            }
        }

        // 5. Cities (upsert on country + state + name).
        $cityCount = 0;
        foreach (self::CITIES as $iso2 => $rows) {
            if (! isset($countryId[$iso2])) {
                continue;
            }
            foreach ($rows as [$sCode, $cityName]) {
                $sKey = $iso2 . ':' . $sCode;
                if (! isset($stateId[$sKey])) {
                    continue; // city's state missing — never orphan a row
                }
                $row = $this->db->table('cities')
                    ->where('country_id', $countryId[$iso2])
                    ->where('state_id', $stateId[$sKey])
                    ->where('name', $cityName)
                    ->get()->getRowArray();
                if ($row === null) {
                    $this->db->table('cities')->insert([
                        'name'         => $cityName,
                        'state_id'     => $stateId[$sKey],
                        'state_code'   => $sCode,
                        'country_id'   => $countryId[$iso2],
                        'country_code' => $iso2,
                        'created_at'   => $now,
                        'updated_at'   => $now,
                    ]);
                    $cityCount++;
                }
            }
        }

        if (is_cli()) {
            fwrite(STDOUT, 'GeoReferenceSeeder: ' . count($regionId) . ' regions, '
                . count($subId) . ' subregions, ' . $count . ' new countries (' . count(self::COUNTRIES) . ' total), '
                . $stateCount . ' new states, ' . $cityCount . " new cities.\n");
        }
    }
}
