#!/usr/bin/env node
/**
 * Copy built CSS/JS to content-hashed filenames and write app/Config/Assets.php.
 */
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pubCss = join(root, 'public/assets/css');
const pubJs = join(root, 'public/assets/js');
mkdirSync(pubCss, { recursive: true });
mkdirSync(pubJs, { recursive: true });

const srcJs = join(root, 'assets/js/app.js');
const builtCss = join(pubCss, 'app.css');
const destJsPlain = join(pubJs, 'app.js');
copyFileSync(srcJs, destJsPlain);

function hashFile(path) {
  if (!existsSync(path)) return 'missing';
  const buf = readFileSync(path);
  return createHash('sha256').update(buf).digest('hex').slice(0, 12);
}

const cssHash = hashFile(builtCss);
const jsHash = hashFile(destJsPlain);
const cssName = `app.${cssHash}.css`;
const jsName = `app.${jsHash}.js`;
if (existsSync(builtCss)) copyFileSync(builtCss, join(pubCss, cssName));
copyFileSync(destJsPlain, join(pubJs, jsName));

const php = `<?php

declare(strict_types=1);

namespace Config;

use CodeIgniter\\Config\\BaseConfig;

/**
 * Content-hashed frontend assets. Regenerated by \`npm run build\`
 * (tools/hash-assets.mjs). Layout reads these; do not edit by hand.
 */
class Assets extends BaseConfig
{
    public string $css = '${cssName}';
    public string $js  = '${jsName}';
}
`;
writeFileSync(join(root, 'app/Config/Assets.php'), php);
console.log('assets:', cssName, jsName);
